name: assignment_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ↓ 以下、授業ノート管理アプリに必要なパッケージを追加
  sqflite: ^2.3.2           # SQLiteデータベースの操作に使用
  path_provider: ^2.1.2     # SQLiteの保存パス取得に必要
  path: ^1.9.0              # ファイルパス操作用（path_providerとセット）
  provider: ^6.1.2          # 状態管理パッケージ（MVVMに近い実装が可能）

  # ↓ UIを整えたい場合に使用（必要であればコメントアウト解除）
  # flutter_slidable: ^3.0.1 # スワイプして削除などのUIに対応

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0

  # ↓ 画像などを使いたい場合、assetsセクションを有効化
  # assets:
  #   - assets/images/


  
